DEVICE          : 'cuda:0'           # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output/v3_860/'         # output folder name used for saving the model, logs and inference results

MODEL:                                    
  NAME          : RCSegFormerV3                                           # name of the model you are using
  BACKBONE      : MiT-B1                                             # model variant
  PRETRAINED    : ''             # backbone model's weight 
  MODEL_PATH    : 'output/v3_860/RCSegFormerV3_MiT-B1_E2.pth'

DATASET:
  NAME          : SplitDataset                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/home/nguyenduong/Data/Real_Data/BCTC/BCTC'                                   # dataset root path
  IGNORE_LABEL  : 255

TRAIN:
  IMAGE_SIZE    : 860    # training image size in (h, w)
  BATCH_SIZE    : 4               # batch size used to train
  EPOCHS        : 300             # number of epochs to train
  EVAL_INTERVAL : 1             # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : false         # use DDP training

LOSS:
  NAME          : OhemCrossEntropy          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.0003        # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : ReduceLROnPlateau    # scheduler name
  PATIENCE       : 10
  # POWER         : 0.9             # scheduler power
  # WARMUP        : 10              # warmup epochs used in scheduler
  # WARMUP_RATIO  : 0.1             # warmup ratio
  
  

EVAL:
  MODEL_PATH    : 'output/v3_768/RCSegFormerV3_MiT-B1_best.pth'     # trained model file path
  IMAGE_SIZE    : 860                           # evaluation image size in (h, w)                       
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : false                                   # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                


TEST:
  MODEL_PATH    : 'output/v3_768/RCSegFormerV3_MiT-B1_best.pth'    # trained model file path
  FILE          : '//home/nguyenduong/Data/Real_Data/real_images'                    # filename or foldername 
  IMAGE_SIZE    : [860]                           # inference image size in (h, w)
  OVERLAY       : true                                    # save the overlay result (image_alpha+label_alpha)